#import <Foundation/Foundation.h>
static NSString *const kUniversalJitScript = @"// Universal JIT Script, last updated 2025-10-10\n"
"const CMD_DETACH = 0;\n"
"const CMD_PREPARE_REGION = 1;\n"
"const CMD_NEW_BREAKPOINTS = 2;\n"
"\n"
"const commands = {\n"
"    [CMD_DETACH]: JIT26Detach,\n"
"    [CMD_PREPARE_REGION]: JIT26PrepareRegion,\n"
"    [CMD_NEW_BREAKPOINTS]: JIT26NewBreakpoints\n"
"};\n"
"\n"
"const legacyCommands = {\n"
"    [0x68]: JIT26NewBreakpoints,\n"
"    [0x69]: JIT26HandleBrk0x69,\n"
"    [0xf00d]: JIT26HandleBrk0xf00d\n"
"};\n"
"\n"
"const LOG_INFO = 1;\n"
"const LOG_VERBOSE = 2;\n"
"let logLevel = LOG_VERBOSE;\n"
"\n"
"function log_verbose(msg) {\n"
"    if (logLevel >= LOG_VERBOSE) {\n"
"        log(msg);\n"
"    }\n"
"}\n"
"\n"
"let tid, x0, x1, x16, pc;\n"
"let detached = false;\n"
"let pid = get_pid();\n"
"let attachResponse = send_command(`vAttach;${pid.toString(16)}`);\n"
"\n"
"log(`pid = ${pid}`);\n"
"log(`attach_response = ${attachResponse}`);\n"
"\n"
"let totalBreakpoints = 0;\n"
"while (!detached) {\n"
"    totalBreakpoints++;\n"
"    log(`Handling signal ${totalBreakpoints}`);\n"
"\n"
"    let brkResponse = send_command(`c`);\n"
"    log_verbose(`brkResponse = ${brkResponse}`);\n"
"\n"
"    if (!brkResponse) continue;\n"
"\n"
"    let tmpMatch = /T[0-9a-f]+thread:(?<tid>[0-9a-f]+);/.exec(brkResponse);\n"
"    tid = tmpMatch ? tmpMatch.groups['tid'] : null;\n"
"    tmpMatch = /20:(?<reg>[0-9a-f]{16});/.exec(brkResponse);\n"
"    pc = tmpMatch ? tmpMatch.groups['reg'] : null;\n"
"    tmpMatch = /10:(?<reg>[0-9a-f]{16});/.exec(brkResponse);\n"
"    x16 = tmpMatch ? tmpMatch.groups['reg'] : null;\n"
"\n"
"    if (!tid || !pc || !x16) {\n"
"        log(`Failed to extract registers: tid=${tid}, pc=${pc}, x16=${x16}`);\n"
"        continue;\n"
"    }\n"
"\n"
"    pc = littleEndianHexStringToNumber(pc);\n"
"    x16 = littleEndianHexStringToNumber(x16);\n"
"\n"
"    let instructionResponse = send_command(`m${pc.toString(16)},4`);\n"
"    log(`instruction at pc: ${instructionResponse}`);\n"
"    if (!instructionResponse) continue;\n"
"\n"
"    let instrU32 = littleEndianHexToU32(instructionResponse);\n"
"\n"
"    if ((instrU32 & 0xFFE0001F)>>>0 != 0xD4200000) {\n"
"        log(`Skipping: instruction was not a brk (was 0x${instrU32.toString(16)})`);\n"
"        let signum = /^T(?<sig>[a-z0-9;]{2})/.exec(brkResponse);\n"
"        signum = signum ? signum.groups['sig'] : null;\n"
"        if (!signum) {\n"
"            log(`Failed to extract signal number: ${signum}`);\n"
"            continue;\n"
"        }\n"
"        log(`Continuing with signal 0x${signum}`);\n"
"        send_command(`vCont;S${signum}:${tid}`);\n"
"        continue;\n"
"    }\n"
"\n"
"    let brkImmediate = extractBrkImmediate(instrU32);\n"
"    log(`BRK immediate: 0x${brkImmediate.toString(16)} (${brkImmediate})`);\n"
"\n"
"    if (legacyCommands[brkImmediate] != undefined) {\n"
"        tmpMatch = /00:(?<reg>[0-9a-f]{16});/.exec(brkResponse);\n"
"        x0 = tmpMatch ? tmpMatch.groups['reg'] : null;\n"
"        tmpMatch = /01:(?<reg>[0-9a-f]{16});/.exec(brkResponse);\n"
"        x1 = tmpMatch ? tmpMatch.groups['reg'] : null;\n"
"        if (!x0 || !x1) {\n"
"            log(`Failed to extract registers: x0=${x0}, x1=${x1}`);\n"
"            continue;\n"
"        }\n"
"        x0 = littleEndianHexStringToNumber(x0);\n"
"        x1 = littleEndianHexStringToNumber(x1);\n"
"\n"
"        let pcPlus4 = numberToLittleEndianHexString(pc + 4n);\n"
"        let pcPlus4Response = send_command(`P20=${pcPlus4};thread:${tid};`);\n"
"        log(`pcPlus4Response = ${pcPlus4Response}`);\n"
"\n"
"        const command = legacyCommands[brkImmediate];\n"
"        command(brkResponse);\n"
"    } else {\n"
"        log(`Skipping breakpoint: brk immediate 0x${brkImmediate.toString(16)} was not handled.`);\n"
"        continue;\n"
"    }\n"
"}\n"
"\n"
"function JIT26Detach() {\n"
"    let detachResponse = send_command(`D`);\n"
"    log_verbose(`detachResponse = ${detachResponse}`);\n"
"    detached = true;\n"
"}\n"
"\n"
"function JIT26NewBreakpoints(brkResponse) {\n"
"    let memResponse = send_command(`m${x0.toString(16)},${x1}`);\n"
"    let scriptText = hexToAscii(memResponse);\n"
"    log_verbose(`Script text: ${scriptText}`);\n"
"    const res = runScriptAndCapture(scriptText);\n"
"    if (res.ok) {\n"
"        log('Script succeeded:', res.value);\n"
"    } else {\n"
"        log('Script failed:', res.name, res.message);\n"
"        log(res.stack);\n"
"    }\n"
"}\n"
"\n"
"function JIT26HandleBrk0x69(brkResponse) {\n"
"    log(`Error: Legacy breakpoint 0x69 detected.`);\n"
"    let putX0Response = send_command(`P0=E0000069;thread:${tid};`);\n"
"    log(`putX0Response = ${putX0Response}`);\n"
"}\n"
"\n"
"function JIT26HandleBrk0xf00d(brkResponse) {\n"
"    const command = commands[x16];\n"
"    if (command === undefined) {\n"
"        log(`Unknown command ${x16.toString(16)}`);\n"
"        return;\n"
"    }\n"
"    log(`Invoking command ${x16.toString(16)}`);\n"
"    command(brkResponse);\n"
"}\n"
"\n"
"function JIT26PrepareRegion(brkResponse) {\n"
"    if (x0 == 0n && x1 == 0n) return;\n"
"    let jitPageAddress = x0;\n"
"    if (x0 == 0n) {\n"
"        let requestRXResponse = send_command(`_M${x1.toString(16)},rx`);\n"
"        if (!requestRXResponse || requestRXResponse.length === 0) {\n"
"            log(`Failed to allocate RX memory`);\n"
"            return;\n"
"        }\n"
"        jitPageAddress = BigInt(`0x${requestRXResponse}`);\n"
"        log(`Allocated JIT page at: 0x${jitPageAddress.toString(16)}`);\n"
"    }\n"
"\n"
"    let prepareJITPageResponse = prepare_memory_region(jitPageAddress, x1);\n"
"    log(`prepareJITPageResponse = ${prepareJITPageResponse}`);\n"
"\n"
"    let putX0Response = send_command(`P0=${numberToLittleEndianHexString(jitPageAddress)};thread:${tid};`);\n"
"    log(`putX0Response = ${putX0Response}`);\n"
"}\n"
"\n"
"function littleEndianHexStringToNumber(hexStr) {\n"
"    const bytes = [];\n"
"    for (let i = 0; i < hexStr.length; i += 2) {\n"
"        bytes.push(parseInt(hexStr.substr(i, 2), 16));\n"
"    }\n"
"    let num = 0n;\n"
"    for (let i = 4; i >= 0; i--) {\n"
"        num = (num << 8n) | BigInt(bytes[i] || 0);\n"
"    }\n"
"    return num;\n"
"}\n"
"\n"
"function numberToLittleEndianHexString(num) {\n"
"    const bytes = [];\n"
"    for (let i = 0; i < 5; i++) {\n"
"        bytes.push(Number(num & 0xFFn));\n"
"        num >>= 8n;\n"
"    }\n"
"    while (bytes.length < 8) bytes.push(0);\n"
"    return bytes.map(b => b.toString(16).padStart(2, '0')).join('');\n"
"}\n"
"\n"
"function littleEndianHexToU32(hexStr) {\n"
"    return parseInt(hexStr.match(/../g).reverse().join(''), 16);\n"
"}\n"
"\n"
"function extractBrkImmediate(u32) {\n"
"    return (u32 >> 5) & 0xFFFF;\n"
"}\n"
"\n"
"function hexToAscii(hexStr) {\n"
"    let str = '';\n"
"    for (let i = 0; i < hexStr.length; i += 2) {\n"
"        const byte = parseInt(hexStr.substr(i, 2), 16);\n"
"        if (byte === 0) break;\n"
"        str += String.fromCharCode(byte);\n"
"    }\n"
"    return str;\n"
"}\n"
"\n"
"function runScriptAndCapture(scriptText) {\n"
"    try {\n"
"        const value = eval(scriptText);\n"
"        return { ok: true, value };\n"
"    } catch (err) {\n"
"        return {\n"
"            ok: false,\n"
"            name: err && err.name,\n"
"            message: err && err.message,\n"
"            stack: err && err.stack\n"
"        };\n"
"    }\n"
"}\n"
"";
static NSString *const kAttachDetachScript = @"// attachDetach.js\n"
"(function() {\n"
"    let pid = get_pid();\n"
"    log(`[AttachDetach] Targeting PID: ${pid}`);\n"
"    \n"
"    let attachResp = send_command(`vAttach;${pid.toString(16)}`);\n"
"    log(`[AttachDetach] Attach response: ${attachResp}`);\n"
"    \n"
"    if (attachResp && attachResp.startsWith('T')) {\n"
"        log(\"[AttachDetach] Successfully attached. Triggering continue...\");\n"
"        let contResp = send_command(\"c\");\n"
"        log(`[AttachDetach] Continue response: ${contResp}`);\n"
"    } else {\n"
"        log(\"[AttachDetach] Failed to attach or unexpected response.\");\n"
"    }\n"
"    \n"
"    // Detach sequence\n"
"    log(\"[AttachDetach] Detaching...\");\n"
"    let detachResp = send_command(\"D\");\n"
"    log(`[AttachDetach] Detach response: ${detachResp}`);\n"
"})();\n"
"";
